server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: app_user
  password: 1710058327
  name: go_api
  sslmode: disable

auth:
  jwt_secret: "kegnezruQWBcDpdPusWiWVywUssUwpr5CmjzZ6NkWUU="
  token_expiry: 24h
