version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: go-api-app
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    image: postgres:15
    container_name: go-api-db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 1710058327
      POSTGRES_DB: go_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d go_api"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
